#   grave=²   1=&  2=é  3="  4='  5=(  6=-  7=è  8=_  9=ç  0=à  minus=)  equal==
#   q=a  w=z  leftbrace=^  rightbrace=$
#   a=q  semicolon=m  apostrophe=ù  backslash=*
#   z=w  m=,  comma=;  dot=:  slash=!  102nd=<

[ids]
*

[main]

tab = timeout(tab, 200, setlayout(colemak))
capslock = timeout(capslock, 200, command(keyd reload))

[colemak:layout]

# 1
grave = noop
1 = S-1
2 = S-2
3 = S-3
4 = S-4
5 = S-5
6 = S-6
7 = S-7
8 = S-8
9 = S-9
0 = S-0
minus = noop
equal = noop
backspace = noop

# 2
tab = timeout(tab, 200, setlayout(main))
q = a
w = z
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = S-comma
leftbrace = noop
rightbrace = noop

# 3
capslock = layer(shift)
a = q
s = r
d = s
f = t
g = g
h = semicolon
j = n
k = e
l = i
semicolon = o
apostrophe = m
backslash = noop

# 4
leftshift = backspace
102nd = w
z = x
x = c
c = d
v = v
b = k
n = k
m = h
comma = 4
dot = 3
slash = noop
rightshift = noop

# 5
leftcontrol = layer(control)
leftmeta = layer(meta)
leftalt = overload(code, oneshot(accent))
rightalt = oneshot(shift)

[control]

# 2
q = C-q
w = C-w
e = C-e
r = C-r
t = C-t
y = C-y
u = C-u
i = C-i
o = C-o
p = C-p

# 3
a = C-a
s = C-s
d = C-d
f = C-f
g = C-g
h = C-h
j = C-j
k = C-k
l = C-l
semicolon = C-semicolon

# 4
102nd = noop
z = C-z
x = C-x
c = C-c
v = C-v
b = C-b
n = C-n

[meta]

# 1
1 = M-1
2 = M-2
3 = M-3
4 = M-4
5 = M-5
6 = M-6
7 = M-7
8 = M-8
9 = M-9
0 = M-0

# 2
q = M-q
w = M-w
e = M-e
r = M-r
t = M-t
y = M-y
u = M-u
i = M-i
o = M-o
p = M-p

# 3
a = M-a
s = M-s
d = M-d
f = M-f
g = M-g
h = M-h
j = M-left
k = M-up
l = M-right
semicolon = M-enter

# 4
leftshift=layer(shift)
102nd = noop
z = M-z
x = M-x
c = M-c
v = M-v
b = M-b
n = M-n
comma = M-down

[code]

# 1
grave = noop
1 = slash
2 = G-0
3 = G-3
4 = rightbrace
5 = S-apostrophe
6 = macro(leftbrace leftbrace)
7 = 1
8 = backslash
9 = 5
0 = minus

# 2
q = delete
w = G-5
e = equal
r = G-minus
t = G-7
y = G-2
u = S-equal
i = 8
o = 6
p = noop

# 3
a = tab
s = G-4
d = dot
f = G-equal
g = home
h = end
j = left
k = up
l = right
semicolon = enter
apostrophe = comma

# 4
z = S-dot
x = noop
c = G-8
v = G-6
b = noop
n = S-m
m = 102nd
comma = down
dot = S-102nd

[accent]
u = macro(leftbrace u)
i = apostrophe
o = macro(S-leftbrace i)
p = macro(S-leftbrace e)

a = 0
s = macro(leftbrace q)
h = macro(leftbrace e)
j = 7
k = 2
l = macro(leftbrace i)
semicolon = macro(leftbrace o)
x = 9

[control+code]
j = C-left
l = C-right
k = up
comma = down
